### ISSUE TITLE
Error in writing the sxs data to cache when using jupyter notebook.

### ISSUE THREAD

**Issue by frcojimenez** [moble/sxs_notebooks#1] opened 2021-09-13 14:16 UTC
Dear all,

I found this error when trying to download the sxs data from a jupyter-lab notebook:

sxs.load("SXS:BBH:0205/Lev/metadata.json",download=True)

'''
Failed to download https://zenodo.org/api/files/e1583c7d-40a1-4efa-a1db-c02e5340ad93/SXS:BBH:0205/Lev3/metadata.json to ~/.cache/sxs/SXS:BBH:0205v5/Lev3/metadata.json; original file remains
'''

I can not reproduce this error when running the same download command from terminal.
My python version is: Python 3.7.3
and jupyter-lab one is: 3.1.11 

And i am running all these commands on: Debian 4.19.160-2

Have any of you found anything similar to that?

thanks in advance!

**Comment by moble** [comment] 2021-09-13 15:09
Sorry to hear it's not working well for you.  Thanks for opening the issue.

I can't reproduce this on either jupyter or plain (terminal) python — that is, the command works in either case.  My main guess is just that there was some temporary problem with zenodo that prevented it from serving the file, or the connection was interrupted, or something similar.  Could you just try it again from jupyter?  Maybe delete `~/.cache/sxs/SXS:BBH:0205v5/Lev3/metadata.json` first?

Now if it still doesn't work, I'm more worried.  The piece of code raising that error is [here](
https://github.com/sxs-collaboration/sxs/blob/fd0c04e3049a2a2fc8b3f9c77000e364c2e004cc/sxs/utilities/downloads.py#L86-L93), and it's pretty simple.  Python has already checked that it can write to `~/.cache/sxs/SXS:BBH:0205v5/Lev3/`, and it has checked that it's gotten a valid response from zenodo.  *Maybe* something is going wrong with `tqdm`, which you could test by trying
```python
sxs.load("SXS:BBH:0205/Lev/metadata.json", download=True, progress=False)
```
which just avoids all the `tqdm` stuff.  The only other things it will use in this case are built-in python functions and the `requests` package, which is probably the most widely used python package there is — both of which mean that the code it's using is extremely well tested.  So if that still fails, it's something utterly crazy.  And if not, it's something wrong with `tqdm`.  Either way, I'll need to see more of the error message to understand what's happening.

**Comment by moble** [comment] 2021-09-13 15:33
Ah, I bet it's `tqdm`.  That's the source of [an error I've just gotten in the latest tests](https://github.com/sxs-collaboration/sxs/runs/3588413424?check_suite_focus=true#step:7:65).  I'll open an issue on that repo.  Meanwhile, use the `progress=False` option.

**Comment by frcojimenez** [comment] 2021-09-13 15:38
Yes, actually this worked. Setting progress=False solves the issue.
Thanks for the answer and for the speed!

best,
Xisco

**Comment by moble** [comment] 2021-09-13 16:14
Okay, so this is definitely a bug in tqdm, rather than this package.  It looks like it will only happen in unusual circumstances, where the interface has weird settings, and when using tqdm versions 4.61.2 through 4.62.2.  So I'll close this as worked-around for now, and we'll just agree to upgrade tqdm whenever it gets fixed.

**Closed as completed by moble** 2021-09-13 16:14 UTC
